###requests
GET http://localhost:3000/pokemon/tyranitar
###Necesario para separar request
POST http://localhost:3000/pokemon/codesthenos
Content-Type: application/json; charset=utf-8

{
  "name": "codesthenos",
  "type": "delusional",
  "moves": [
    "smoke"
  ]
}