### Recuperar todas las peliculas
GET http://localhost:3210/movies
### Recuperar una pelicula por id
GET http://localhost:3210/movies/66673d3c7939d0163ac8a550
### Recuperar las peliculas de un genero
GET http://localhost:3210/movies/genre/teRRor
### Recuperar las peliculas de un director
GET http://localhost:3210/movies?director=Frank
### Recuperar las peliculas de un director concreto y rating > el numero que ponga aqui
GET http://localhost:3210/movies?director=alberto%20ARMAS&rate=10
### Solo rate
GET http://localhost:3210/movies?rate=8.9
### Creando una pelicula con POST
POST http://localhost:3210/movies
Content-Type: application/json; charset=utf-8

{
  "title": "Slasher",
  "year": 2022,
  "director": "Alberto Armas",
  "poster": "https://pics.filmaffinity.com/Slasher-171881556-large.jpg",
  "genre": [
    "Terror",
    "Slasher",
    "Comedy"
  ],
  "duration": 101,
  "rate": 2
}
### forzando error en POST para verificar validacion
POST http://localhost:3210/movies
Content-Type: application/json; charset=utf-8

{
  "title": 35505,
  "year": 2022,
  "director": "Alberto Armas",
  "poster": "https://pics.filmaffinity.com/Slasher-171881556-large.jpg",
  "genre": [
    "Terror",
    "Slasher",
    "Comedy"
  ],
  "duration": 101,
  "rate": 11
}
### probamos a borrar una pelicula
DELETE http://localhost:3210/movies/27936561-3b12-11ef-856a-0a0027000005
### actualizar una parte de una pelicula con PATCH
PATCH http://localhost:3210/movies/66673d3c7939d0163ac8a550
Content-Type: application/json; charset=utf-8

{
  "rate": 10
}